# Generated by Django 5.0.2 on 2024-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
