# Generated by Django 5.0.2 on 2024-12-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='compte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='app.compte'),
        ),
    ]
