# Generated by Django 5.0.2 on 2024-12-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_event',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_event', to='app.event'),
        ),
    ]
