# Generated by Django 5.0.2 on 2024-12-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_comment_event_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
