# Generated by Django 5.0.2 on 2024-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comment_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannequin',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
