# Generated by Django 5.0.2 on 2024-12-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_mannequin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannequin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mannequin', to='app.profile'),
        ),
    ]
