# Generated by Django 5.0.2 on 2024-12-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='app.service'),
        ),
    ]
