# Generated by Django 5.0.2 on 2024-12-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='Post',
            new_name='post',
        ),
    ]
